spring:
  datasource.url: jdbc:postgresql://localhost:5432/odontoflow
  datasource.username: postgres
  datasource.password: admin
  datasource.driver-class-name: org.postgresql.Driver
  application.name: odontoflow
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret: minha-chave-super-secreta
    expiration: 3600000